#!/usr/bin/env bash

# This script will remove files/folders that updatra created (Note: It will not delete dependencies installed)

# Colors
RED='\033[0;91m'
RED_BLINK='\033[6;91m'
GREEN_BLINK='\033[6;92m'
GREEN='\033[0;92m'
NC='\033[0m'

# Tell user what it does
echo -e "${GREEN}This will uninstall any files/folders created by updatera"${GREEN_BLINK}
echo ""
read -p "Press any key to continue..." -n1 -s
clear

# Delete /home/username/.local/src/libretro-super if it exists
if [[ -d "${HOME}/.local/src/libretro-super" ]]; then
  echo -e "${GREEN}Removing folder ${RED}libretro-super ${GREEN}from ${RED}${HOME}/.local/src${NC}"
  rm -R -f "${HOME}/.local/src/libretro-super"
else
  echo -e "${RED}${HOME}/.local/src/libretro-super ${GREEN}doesn't exist${NC}"
  echo ""
  echo -e "${GREEN}Nothing to remove${NC}"
fi
sleep 3
clear

# See if /home/username/.local/src exists and empty, and delete if it is
if [[ -d "${HOME}/.local/src" ]] && [[ -z "$(ls -A "${HOME}/.local/src")" ]]; then
  echo -e "${GREEN}Removing empty folder ${RED}src ${GREEN}from ${RED}${HOME}/.local${NC}"
  rm -R -f "${HOME}/.local/src"
elif [[ -d "${HOME}/.local/src" ]] && [[ ! -z "$(ls -A "${HOME}/.local/src")" ]]; then
  echo -e "${RED}${HOME}/.local/src ${GREEN}exists, but not empty so not removed${NC}"
else
  echo -e "${RED}${HOME}/.local/src ${GREEN}doesn't exist${NC}"
  echo ""
  echo -e "${GREEN}Nothing to remove${NC}"
fi
sleep 3
clear

# Delete "retroarch" from /home/username/.local/bin if it exists
if [[ -f "${HOME}/.local/bin/retroarch" ]]; then
  echo -e "${GREEN}Removing ${RED}retroarch ${GREEN}from ${RED}${HOME}/.local/bin${NC}"
  rm -f "${HOME}/.local/bin/retroarch"
else
  echo -e "${RED}${HOME}/.local/bin/retroarch ${GREEN}doesn't exist${NC}"
  echo ""
  echo -e "${GREEN}Nothing to remove${NC}"
fi
sleep 3
clear

# Delete "updatera" from /home/username/.local/bin if it exists
if [[ -f "${HOME}/.local/bin/updatera" ]]; then
  echo -e "${GREEN}Removing ${RED}updatera ${GREEN}from ${RED}${HOME}/.local/bin${NC}"
  rm -f "${HOME}/.local/bin/updatera"
else
  echo -e "${RED}${HOME}/.local/bin/updatera ${GREEN}doesn't exist${NC}"
  echo ""
  echo -e "${GREEN}Nothing to remove${NC}"
fi
sleep 3
clear

# See if /home/username/.local/bin is empty, and delete if it is
if [[ -d "${HOME}/.local/bin" ]] && [[ -z "$(ls -A "${HOME}/.local/bin")" ]]; then
  echo -e "${GREEN}Removing empty folder ${RED}bin ${GREEN}from ${RED}${HOME}/.local${NC}"
  rm -R -f "${HOME}/.local/bin"
elif [[ -d "${HOME}/.local/bin" ]] && [[ ! -z "$(ls -A "${HOME}/.local/bin")" ]]; then
  echo -e "${RED}${HOME}/.local/bin ${GREEN}exists, but not empty so not removed${NC}"
else
  echo -e "${RED}${HOME}/.local/bin ${GREEN}doesn't exist${NC}"
  echo ""
  echo -e "${GREEN}Nothing to remove${NC}"
fi
sleep 3
clear

# Delete /home/username/.config/retroarch if it exists
if [[ -d "${HOME}/.config/retroarch" ]]; then
  echo -e "${GREEN}Removing folder ${RED}retroarch ${GREEN}from ${RED}${HOME}/.config${NC}"
  rm -R -f "${HOME}/.config/retroarch"
else
  echo -e "${RED}${HOME}/.config/retroarch ${GREEN}doesn't exist${NC}"
  echo ""
  echo -e "${GREEN}Nothing to remove${NC}"
fi
sleep 3
clear

# Delete "Retroarch" shortcut from /home/username/.local/share/applications
if [[ -f "${HOME}/.local/share/applications/retroarch.desktop" ]]; then
  echo -e "${GREEN}Removing ${RED}retroarch.desktop ${GREEN}from ${RED}${HOME}/.local/share/applications${NC}"
  rm -f "${HOME}/.local/share/applications/retroarch.desktop"
else
  echo -e "${RED}${HOME}/.local/share/applications/retroarch.desktop ${GREEN}doesn't exist${NC}"
  echo ""
  echo -e "${GREEN}Nothing to remove${NC}"
fi
sleep 3
clear

# Delete " Update Retroarch" shortcut from /home/username/.local/share/applications
if [[ -f "${HOME}/.local/share/applications/update-retroarch.desktop" ]]; then
  echo -e "${GREEN}Removing ${RED}update-retroarch.desktop ${GREEN}from ${RED}${HOME}/.local/share/applications${NC}"
  rm -f "${HOME}/.local/share/applications/update-retroarch.desktop"
else
  echo -e "${RED}${HOME}/.local/share/applications/update-retroarch.desktop ${GREEN}doesn't exist${NC}"
  echo ""
  echo -e "${GREEN}Nothing to remove${NC}"
fi
sleep 3
clear

echo -e "${GREEN}All files/folders that updatera has created, have been removed${NC}"
echo ""
echo -e "${GREEN}No build dependencies have been removed${NC}"
echo -e "${GREEN}(Removing build dependencies is known to break systems)${RED_BLINK}"
echo ""
read -p "Press any key to exit..." -n1 -s
